apiVersion: v1
kind: ConfigMap
metadata:
  name: eno-binder-config
  namespace: eno-system
data:
  eno-binder-config: |+
    apiVersion: godelbinder.config.kubewharf.io/v1beta1
    kind: EnoBinderConfiguration
    profile:
      plugins:
        victimChecking:
          pluginCollections:
            - plugins:
                - name: PDBChecker
              enableQuickPass: false
