apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  namespace: eno-system
  labels:
    component: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-dispatcher
  template:
    metadata:
      labels:
        app: eno-dispatcher
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      serviceAccountName: eno
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: dispatcher
          image: eno-local:latest
          imagePullPolicy: Never
          command: ["/usr/local/bin/dispatcher"]
          ports:
            - containerPort: 10351
              name: metrics
              protocol: TCP
          args:
            - "--leader-elect=false"
            - "--tracer=noop"
            - "--v=5"
          resources:
            limits:
              cpu: "2"
              memory: 4G
            requests:
              cpu: "1"
              memory: 2G
