apiVersion: v1
kind: ConfigMap
metadata:
  name: eno-scheduler-config
  namespace: eno-system
data:
  eno-scheduler-config: |+
    apiVersion: godelscheduler.config.kubewharf.io/v1beta1
    kind: EnoSchedulerConfiguration
    subClusterKey: subCluster
    defaultProfile:
      disablePreemption: false
