apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
    - grafana.dsif.dawlmkjckdev01.ienergycloud.solutions
  gateways:
    - svc-gateway.plat-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana.external.local
            port:
              number: 30091
